# Generated by Django 2.2 on 2019-12-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191204_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sportwear'), ('OW', 'Outwear'), ('W', 'Watch'), ('MP', 'Mobile Phone'), ('SP', 'SmartPhone'), ('L', 'Laptop'), ('Ba', 'Bagpack'), ('La', 'Lamp'), ('Te', 'Television'), ('Sm', 'Smartwatch'), ('Sh', 'shoes')], max_length=2),
        ),
    ]
